window_title: "SeeK-path: the k-path finder and visualizer"
page_title: "SeeK-path: the k-path finder and visualizer"

templates:
  how_to_cite: "how_to_cite.html"
  about: "custom_about.html"
  select_content: "visualizer_select_example.html"

use_upload_structure_block: True

additional_accordion_entries:
  - header: "SeeK-path definitions and advantages"
    template_page: definitions.html

about_section_title: "What SeeK-path does"
